### ISSUE TITLE
Fan doesn't start spinning on boot until service is restarted.

### ISSUE THREAD

**Issue by christran** [Pyrestone/jetson-fan-ctl#10]
The automagic-fan service is active and running on boot but the fan doesn't start spinning unless the service gets restarted.

I was able to fix it by adding this line to the service file.

`ExecStartPre=/bin/sleep 5`

**Comment by Pyrestone** [comment]
Ok, can you create a pull request?
________________________________
From: Chris Tran ***@***.***>
Sent: Sunday, August 8, 2021 10:31:12 AM
To: Pyrestone/jetson-fan-ctl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Pyrestone/jetson-fan-ctl] Fan doesn't start spinning on boot until service is restarted. (#10)


The automagic-fan service is active and running on boot but the fan doesn't start spinning unless the service gets restarted.

I was able to fix it by adding this line to the service file.

ExecStartPre=/bin/sleep 5

**Comment by Pyrestone** [comment]
fixed by your PR
