### ISSUE TITLE
Is your script supposed to work with another kernel and set of patches ?

### ISSUE THREAD

**Issue by Marietto2008** [Pyrestone/jetson-fan-ctl#18]
I've recompiled the kernel because I wanted to enable kvm. The commands that I have issued are :

```
git clone https://github.com/OE4T/linux-tegra-4.9.git
cd linux-tegra-4.9
git checkout oe4t-patches-l4t-r32.7.3
cp /proc/config.gz .
gunzip config.gz
mv config .config
make menuconfig —> (enable kvm)
make -j4
make -j4 modules_install
make -j4 Image
mv /boot/Image-kvm Image2-kvm
cp arch/arm64/boot/Image /boot/Image

the dtb file to use is called : tegra210-p3448-0000-p3449-0000-a02.dtb 
and the extlinux.conf is something like this :

TIMEOUT 30
DEFAULT primary

MENU TITLE L4T boot options

LABEL primary
MENU LABEL primary kernel
LINUX /boot/Image
INITRD /boot/initrd
FDT /boot/tegra210-p3448-0000-p3449-0000-a02.dtb
APPEND ${cbootargs} quiet root=/dev/mmcblk0p1 rw rootwait rootfstype=ext4 console=ttyS0,115200n8 console=tty0 fbcon=map:0 net.ifnames=0
```

Unfortunately Xfce freezes a second before to be fully loaded and I suspect that the cause is your script. Is it supposed to work on the scenario that I have explained ? Yes,I've removed your script,giving these commands :
```

systemctl disable automagic-fan
mv /usr/local/bin/automagic-fan /usr/local/bin/automagic-fan_
mv /lib/systemd/system/automagic-fan.service /lib/systemd/system/automagic-fan.service_
mv /etc/automagic-fan /etc/automagic-fan_
```

but the problem still there. xfce won't fully load. But i still suspect that the cause is your script. I would like to know your opinion.

**Comment by Pyrestone** [comment]
if you disabled the service then it is not running (i.e. does nothing and didn't cause your crash). If your pc still crashes after disabling the fan script then it is not the cause. Your custom kernel stuff sounds much more likely to cause that, so if I were you I'd look into that, or according driver issues.
The worst thing a python script can do is have an exception, which just stops the script and nothing more.
