### ISSUE TITLE
Errors in GPU frequency

### ISSUE THREAD

**Issue by museum-future** [Pyrestone/jetson-fan-ctl#4]
I get the following when running the script.

> =>sudo service automagic-fan status
> ● automagic-fan.service - Automagic fan control
>    Loaded: loaded (/lib/systemd/system/automagic-fan.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sun 2020-05-10 19:35:19 CEST; 13h ago
>  Main PID: 2579 (python3)
>     Tasks: 1 (limit: 4163)
>    CGroup: /system.slice/automagic-fan.service
>            └─2579 /usr/bin/python3 -u /usr/local/bin/automagic-fan/fanctl.py
> 
> May 10 19:35:19 nano systemd[1]: Started Automagic fan control.
> May 10 19:35:24 nano python3[2579]: Maximizing clock speeds with jetson_clocks
> May 10 19:35:24 nano python3[2579]: /usr/bin/jetson_clocks: line 269: : No such file or directory
> May 10 19:35:24 nano python3[2579]: /usr/bin/jetson_clocks: line 270: : No such file or directory
> May 10 19:35:24 nano python3[2579]: Error: Failed to max GPU frequency!
> May 10 19:35:24 nano python3[2579]: Setup complete.
> May 10 19:35:24 nano python3[2579]: Running normally.

Lines 269/270

> 			echo 0 > "${GPU_RAIL_GATE}"
> 			cat "${GPU_MAX_FREQ}" > "${GPU_MIN_FREQ}"

**Comment by Pyrestone** [comment]
workaround: open the config file in your favorite editor (e.g. nano):  
`sudo nano /etc/automagic-fan/config.json`

 and change  
`"MAX_PERF":1`   
to   
`"MAX_PERF":0`

the main issue here is probably in your `jetson_clocks` tool, which this script calls, but it is not part of the automagic-fan package. It comes with jetpack.

**Comment by sunfic** [comment]
I think we need to reopen this one. 
the issue is when the service start the GPU is not ready yet. solution is delay the service until GPU ready. 

add 

    After=nvargus-daemon.service

inside Unit section of automagic-fan.service file will do it

**Comment by Pyrestone** [comment]
@sunfic are you sure that all users even have the nvargus-daemon service installed?

Otherwise that line might prevent the service from ever starting up...

I think a better solution might be to just add a try-catch block around the jetson-clocks call.

**Comment by sunfic** [comment]
> @sunfic are you sure that all users even have the nvargus-daemon service installed?
> 
> Otherwise that line might prevent the service from ever starting up...
> 
> I think for now a better solution might be to just add a try-catch block around the jetson-clocks call.

nvargus-daemon is the default component within jetson pack. Unless user uninstall it on purpose it is always there and starts with system regardless you have camera hooking on or not. 

Capturing the error from jetson-clocks is also good idea.
