### ISSUE TITLE
jetson_stats as well as jetson-fan-ctl

### ISSUE THREAD

**Issue by js1972** [Pyrestone/jetson-fan-ctl#5]
I have jetson_stats on my machine and it has a service that controls when jetson_clocks is run... Will jetson-fan-ctl upset that given the config files has a MAX_PERF value which causes jetson_clocks to be run?

**Comment by Pyrestone** [comment]
Hi,  
if you control jetson_clocks in another program, I'd recommend setting MAX_PERF to 0 and just let your other program handle it.  

The MAX_PERF flag only runs jetson_clocks once at boot time.  
If you disable MAX_PERF, then automagic-fan will only control the fan speeds.

Your other program would probably just override the one-off value set by automagic-fan, but if you want to be safe, then just disable MAX_PERF and let your other program handle clock speeds.

Hope this helps!

**Comment by js1972** [comment]
Thanks @Pyrestone. That’s what I was thinking so have set to 0. 
I just notice that the power setting on the Xavier is dropped back to the bottom setting every. One and then and I’m trying to work out why. 

Anyway great stuff on the fan control!!   ;-)
